/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'John' at '12/25/15 6:10 PM' with Gradle 2.9
 *
 * @author John, @date 12/25/15 6:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
